apiVersion: v1
kind: Pod
metadata:
  name: nginx3
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: disktype
            operator: In
            values:
            - ssd            
  containers:
  - name: nginx3
    image: nginx
    imagePullPolicy: IfNotPresent

