---
apiVersion: batch/v1
kind: Job
metadata:
  name: countnumberjob
spec:
  template:
    metadata:
      name: countnumber
    spec:
      containers:
      - name: countnumber
        image: busybox
        command: ['sh', '-c', 'for i in {1,2,3,4,5,6,7,8,9}; do echo $i; sleep 5; done']
      restartPolicy: OnFailure
